export const user = [];


export const slider1 = [
    {
        "id": "1",
        "imageUrl1": "../images/slider1.png",
        "imageUrl2": "../images/slider2.png",
        "imageUrl3": "../images/slider3.png",
        "text1": "برندات أطفال عالمية",
        "text2": "احدث ملابس للاطفات",
        "text3": "برندات نسائي عالمية"
    },
    {
        "id": "2",
        "imageUrl1": "../images/form.png",
        "imageUrl2": "../images/slider2.png",
        "imageUrl3": "../images/slider3.png",
        "text1": "برندات نسائي عالمية",
        "text2": "احدث ادوات الجمال",
        "text3": "برندات نسائي عالمية"
    },
    {
        "id": "3",
        "imageUrl1": "../images/form2.png",
        "imageUrl2": "../images/slider2.png",
        "imageUrl3": "../images/slider3.png",
        "text1": "برندات رجالي عالمية",
        "text2": "احدث ادوات الجمال",
        "text3": "برندات نسائي عالمية"
    }
];


export const cart = [
    {
        "imageUrl": "../images/products/pro8.png",
        "productName": "بلوزة بيضاء",
        "price": "800",
        "Quant": 1,
        "discountedPrice": "800",
        "categories": "clothes",
        "trademarks": "Apple",
        "color": "white",
        "weight": "l",
        "id": "1"
    }
];


export const Product = [
    {
        "id": "1",
        "imageUrl": "../images/products/pro8.png",
        "imageUr2": "../images/products/pro1.png",
        "imageUr3": "../images/products/pro7.png",
        "imageUr4": "../images/products/pro2.png",
        "imageUr5": "",
        "price": "800",
        "discountedPrice": "800",
        "productName": "بلوزة بيضاء",
        "watch": "6",
        "categories": "clothes",
        "trademarks": "Apple",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "l"
    },
    {
        "id": "2",
        "imageUrl": "../images/products/shoes/3.2.jpg",
        "imageUr2": "../images/products/shoes/3.0.jpg",
        "imageUr3": "../images/products/shoes/3.4.jpg",
        "imageUr4": "",
        "imageUr5": "",
        "price": "400",
        "discountedPrice": "480",
        "productName": "حذاء سهل الارتداء كلاسيكي مصنوع من الجلد للرجال من رومبا",
        "watch": "6",
        "categories": "shoes",
        "trademarks": "samsung",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "xl"
    },
    {
        "id": "3",
        "imageUrl": "../images/products/41TbKFKtAEL._AC_.jpg",
        "imageUr2": "../images/products/41Pa07zjC6L._AC_.jpg",
        "imageUr3": "../images/products/41kFaS2e9yL._AC_.jpg",
        "imageUr4": "../images/products/21rayG4HF5L._AC_.jpg",
        "imageUr5": "../images/products/31-xnIiTuKL._AC_.jpg",
        "price": "950",
        "discountedPrice": "1000",
        "productName": "ساعة مع اتصال بلوتوث",
        "watch": "6",
        "categories": "accessories",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "x"
    },
    {
        "id": "4",
        "imageUrl": "../images/products/419haTrJQPL._AC_SX679_.jpg",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "600",
        "discountedPrice": "670",
        "productName": "جوارب قطنية",
        "watch": "6",
        "categories": "clothes",
        "trademarks": "Sony",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "m"
    },
    {
        "id": "5",
        "imageUrl": "../images/products/41W8RUawyUL._AC_UL400_.jpg",
        "imageUr2": "../images/products/31GKwu-pXGL._AC_SY575_.jpg",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "500",
        "discountedPrice": "550",
        "productName": "S925 خاتم من الفضة الاسترليني الخالصة، خاتم الماس فاخر، خاتم زفاف انثوي، لوازم زفاف، خاتم واحد",
        "watch": "6",
        "categories": "jewelry",
        "trademarks": "samsung",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "l"
    },
    {
        "id": "6",
        "imageUrl": "../images/products/pro6.png",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "799",
        "discountedPrice": "1199",
        "productName": "جاكيت اطفال",
        "watch": "6",
        "categories": "clothes",
        "trademarks": "Lenovo",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "blue",
        "weight": "s"
    },
    {
        "id": "7",
        "imageUrl": "../images/products/pro1.png",
        "imageUr2": "../images/products/pro7.png",
        "imageUr3": "../images/products/pro8.png",
        "imageUr4": "../images/products/pro2.png",
        "imageUr5": "",
        "price": "582",
        "discountedPrice": "754",
        "productName": "فستان اسود",
        "watch": "12",
        "categories": "clothes",
        "trademarks": "Apple",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "xl"
    },
    {
        "id": "8",
        "imageUrl": "../images/products/pro7.png",
        "imageUr2": "../images/products/pro1.png",
        "imageUr3": "../images/products/pro8.png",
        "imageUr4": "../images/products/pro2.png",
        "imageUr5": "",
        "price": "1200",
        "discountedPrice": "1500",
        "productName": "فستان ابيض",
        "watch": "12",
        "categories": "clothes",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "l"
    },
    {
        "id": "9",
        "imageUrl": "../images/products/818WdJZwDDL._AC_SX679_.jpg",
        "imageUr2": "../images/products/71i1ebvMJ0L._AC_SX679_.jpg",
        "imageUr3": "../images/products/915YaZMzZdL._AC_SX679_.jpg",
        "imageUr4": "../images/products/91h19pY+ojL._AC_SY575_.jpg",
        "imageUr5": "",
        "price": "1200",
        "discountedPrice": "1500",
        "productName": "سلسلة دهب",
        "watch": "12",
        "categories": "jewelry",
        "trademarks": "Sony",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "xl"
    },
    {
        "id": "10",
        "imageUrl": "../images/products/614-KmphLHL._AC_SL1000_.jpg",
        "imageUr2": "../images/products/51RBnGGb6GL._AC_SL1000_.jpg",
        "imageUr3": "../images/products/61yxUNcYjTL._AC_SL1000_.jpg",
        "imageUr4": "../images/products/61ckfbfWrfL._AC_SL1000_.jpg",
        "imageUr5": "../images/products/21fuRmxKmhL._AC_SL1000_.jpg",
        "price": "10400",
        "discountedPrice": "10700",
        "productName": "تلفزيون سمارت ليد 50 بوصة الترا اتش دي HD",
        "watch": "12",
        "categories": "electronics",
        "trademarks": "Apple",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "blue",
        "weight": "x"
    },
    {
        "id": "11",
        "imageUrl": "../images/products/61xLyvhybuL._AC_SX522_.jpg",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "1000",
        "discountedPrice": "1100",
        "productName": "قميص اسود",
        "watch": "12",
        "categories": "clothes",
        "trademarks": "Sony",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "l"
    },
    {
        "id": "12",
        "imageUrl": "../images/products/pro4.png",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "700",
        "discountedPrice": "750",
        "productName": "فستان اطفال ابيض",
        "watch": "12",
        "categories": "clothes",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "m"
    },
    {
        "id": "13",
        "imageUrl": "../images/products/pro9.png",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "200",
        "discountedPrice": "300",
        "productName": "تيشيرت ابيض",
        "watch": "18",
        "categories": "clothes",
        "trademarks": "Apple",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "xl"
    },
    {
        "id": "14",
        "imageUrl": "../images/products/pro2.png",
        "imageUr2": "../images/products/pro7.png",
        "imageUr3": "../images/products/pro1.png",
        "imageUr4": "../images/products/pro8.png",
        "imageUr5": "",
        "price": "2200",
        "discountedPrice": "2500",
        "productName": "فستان اخضر",
        "watch": "18",
        "categories": "clothes",
        "trademarks": "Lenovo",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "green",
        "weight": "xl"
    },
    {
        "id": "15",
        "imageUrl": "../images/products/41UQjc6LKnL._AC_SL1500_.jpg",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "500",
        "discountedPrice": "550",
        "productName": "مروحه ستاند شبح من فريش",
        "watch": "18",
        "categories": "electronics",
        "trademarks": "samsung",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "l"
    },
    {
        "id": "16",
        "imageUrl": "../images/products/71GRwmYgDmL._AC_SX679_.jpg",
        "imageUr2": "../images/products/51R3LmpvC7L._AC_.jpg",
        "imageUr3": "../images/products/71xyOLInPSL._AC_SX679_.jpg",
        "imageUr4": "../images/products/41-YVzdvNUS._AC_.jpg",
        "imageUr5": "../images/products/81DP94mD2dS._AC_SX679_.jpg",
        "price": "2000",
        "discountedPrice": "2100",
        "productName": "سوار فاخر من جلد اصلي مصنوع يدويا بمشبك اسود لساعة سامسونج جالاكسي بني",
        "watch": "18",
        "categories": "accessories",
        "trademarks": "Johnson & Handson",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "x"
    },
    {
        "id": "17",
        "imageUrl": "../images/products/51hH8HpO13S._AC_SX569_.jpg",
        "imageUr2": "../images/products/61zioQHmYVS._AC_SX569_.jpg",
        "imageUr3": "../images/products/41+h86tljMS._AC_SX569_.jpg",
        "imageUr4": "../images/products/51oXKa3MjqS._AC_SX569_.jpg",
        "imageUr5": "../images/products/51kBmFd-1VS._AC_SX569_.jpg",
        "price": "1200",
        "discountedPrice": "1500",
        "productName": "بدلة سوداء",
        "watch": "18",
        "categories": "clothes",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "xl"
    },
    {
        "id": "18",
        "imageUrl": "../images/products/shoes/2.jpg",
        "imageUr2": "../images/products/shoes/2.1.jpg",
        "imageUr3": "../images/products/shoes/2.2.jpg",
        "imageUr4": "../images/products/shoes/2.3.jpg",
        "imageUr5": "../images/products/shoes/2.4.jpg",
        "price": "1250",
        "discountedPrice": "1300",
        "productName": "حذاء برقبة ريفولت هاي تي اكس للنساء من بالاديوم، اسود، مقاس 38 EU",
        "watch": "18",
        "categories": "shoes",
        "trademarks": "Johnson & Handson",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "xl"
    },
    {
        "id": "19",
        "imageUrl": "../images/products/51a5RJlj7dL._AC_SX679_.jpg",
        "imageUr2": "../images/products/51W7isiyT+L._AC_.jpg",
        "imageUr3": "../images/products/51S9e54pceL._AC_SX679_.jpg",
        "imageUr4": "",
        "imageUr5": "",
        "price": "1500",
        "discountedPrice": "1800",
        "productName": "بليزر للرجال من كوب",
        "watch": "24",
        "categories": "clothes",
        "trademarks": "Lenovo",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "xl"
    },
    {
        "id": "20",
        "imageUrl": "../images/products/51SoC0dtvFL._AC_UL400_.jpg",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "95",
        "discountedPrice": "100",
        "productName": "رابطة عنق",
        "watch": "24",
        "categories": "accessories",
        "trademarks": "samsung",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "l"
    },
    {
        "id": "21",
        "imageUrl": "../images/products/61Nv+eZqQxL._AC_SY879_.jpg",
        "imageUr2": "../images/products/61WZoOGjRrL._AC_SL1500_.jpg",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "150",
        "discountedPrice": "200",
        "productName": "رف احذية بلاستيكي",
        "watch": "24",
        "categories": "furniture",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "xl"
    },
    {
        "id": "22",
        "imageUrl": "../images/products/513YEm+nl9L._AC_SX522_.jpg",
        "imageUr2": "../images/products/41oUJ1Xqw1L._AC_SX522_.jpg",
        "imageUr3": "../images/products/41wkg2aylbL._AC_SX522_.jpg",
        "imageUr4": "",
        "imageUr5": "",
        "price": "300",
        "discountedPrice": "320",
        "productName": "بنطلون ابيض",
        "watch": "24",
        "categories": "clothes",
        "trademarks": "Sony",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "x"
    },
    {
        "id": "23",
        "imageUrl": "../images/products/shoes/61KVmniEuDL._AC_SY625_.jpg",
        "imageUr2": "../images/products/shoes/41cv92USNFL._AC_SY625_.jpg",
        "imageUr3": "../images/products/shoes/51KEnGvM+kL._AC_SY625_.jpg",
        "imageUr4": "../images/products/shoes/41fptGkruOL._AC_SY625_.jpg",
        "imageUr5": "",
        "price": "1200",
        "discountedPrice": "1500",
        "productName": "انتا حذاء رياضي ايه سيلو للنساء",
        "watch": "24",
        "categories": "shoes",
        "trademarks": "Johnson & Handson",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "m"
    },
    {
        "id": "24",
        "imageUrl": "../images/products/61TXYW-EQ9L._AC_SL1080_.jpg",
        "imageUr2": "../images/products/61nTdp14aIL._AC_SL1080_.jpg",
        "imageUr3": "../images/products/51fcAEUCo3L._AC_SL1080_.jpg",
        "imageUr4": "../images/products/51GN8jlEB6L._AC_SL1080_.jpg",
        "imageUr5": "../images/products/51mlYNmFsVL._AC_SL1080_.jpg",
        "price": "200ج.م",
        "discountedPrice": "500ج.م",
        "productName": "مرتبة تطرية من سنوز",
        "watch": "24",
        "categories": "furniture",
        "trademarks": "Apple",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "s"
    },
    {
        "id": "25",
        "imageUrl": "../images/products/71QVB-yEfQL._AC_SX679_.jpg",
        "imageUr2": "../images/products/618XcBpJL+L._AC_SX679_.jpg",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "290",
        "discountedPrice": "300",
        "productName": "تيشرت عليه شعار النادي الاهلي الرسمي للجنسين لمشجعي النادي الاهلي",
        "watch": "30",
        "categories": "clothes",
        "trademarks": "samsung",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "red",
        "weight": "xl"
    },
    {
        "id": "26",
        "imageUrl": "../images/products/pro5.png",
        "imageUr2": "",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "2900",
        "discountedPrice": "3500",
        "productName": "قميص ازرق",
        "watch": "30",
        "categories": "clothes",
        "trademarks": "Google",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "blue",
        "weight": "l"
    },
    {
        "id": "27",
        "imageUrl": "../images/products/61Ss0tkcauL._AC_SL1500_.jpg",
        "imageUr2": "../images/products/51NcdnxX8EL._AC_SL1500_.jpg",
        "imageUr3": "../images/products/4127h5Y15qL._AC_SL1500_.jpg",
        "imageUr4": "../images/products/41WUf40A6ZL._AC_SL1500_.jpg",
        "imageUr5": "",
        "price": "2800",
        "discountedPrice": "3000",
        "productName": "برافو مكتب مع ارفف - ابيض",
        "watch": "30",
        "categories": "furniture",
        "trademarks": "Lenovo",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "white",
        "weight": "l"
    },
    {
        "id": "28",
        "imageUrl": "../images/products/61GQqx-NA4L._AC_SX679_.jpg",
        "imageUr2": "../images/products/61i8JDGGh7L._AC_SX679_.jpg",
        "imageUr3": "../images/products/71PXjZaylFL._AC_SX679_.jpg",
        "imageUr4": "../images/products/71YMgzkt8RL._AC_SX679_.jpg",
        "imageUr5": "../images/products/613qwQDi0fL._AC_SX679_.jpg",
        "price": "200",
        "discountedPrice": "300",
        "productName": "بلوزة للنساء من اندورا",
        "watch": "30",
        "categories": "clothes",
        "trademarks": "Sony",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "yellow",
        "weight": "xl"
    },
    {
        "id": "29",
        "imageUrl": "../images/products/414vWxXSdYL._AC_.jpg",
        "imageUr2": "../images/products/41j4bZ8ww8L._AC_.jpg",
        "imageUr3": "../images/products/51fN5Z9dALL._AC_SL1500_.jpg",
        "imageUr4": "",
        "imageUr5": "",
        "price": "190ج.م",
        "discountedPrice": "210ج.م",
        "productName": " بين باج كمفرت من بينجوان - ازرق",
        "watch": "30",
        "categories": "other",
        "trademarks": "Johnson & Handson",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "blue",
        "weight": "l"
    },
    {
        "id": "30",
        "imageUrl": "../images/products/715pUQm6RAL._AC_SL1500_.jpg",
        "imageUr2": "../images/products/51qCSGD3LRL._AC_SX569_.jpg",
        "imageUr3": "",
        "imageUr4": "",
        "imageUr5": "",
        "price": "3100ج.م",
        "discountedPrice": "3300ج.م",
        "productName": "طقم عجلات لكرسي المكتب (5 عجلات)",
        "watch": "30",
        "categories": "other",
        "trademarks": "Lenovo",
        "desc": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "color": "black",
        "weight": "s"
    }

];



export const comments = [
    {
        "name": "",
        "email": "",
        "comment": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة\n                                عدد الحروف التى يولدها التطبيق",
        "title": "منتج رائع. التعبئة والتغليف كانت جيدة أيضا",
        "id": "1"
    },
    {
        "name": "",
        "email": "",
        "comment": "fgfdsgfdgggfgfcccbcvbgd",
        "title": "fdsf",
        "id": "2"
    },
    {
        "name": "",
        "email": "",
        "comment": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "title": "منتج رائع. التعبئة والتغليف كانت جيدة أيضا",
        "id": "3"
    },
    {
        "name": "",
        "email": "",
        "comment": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "title": "منتج رائع. التعبئة والتغليف كانت جيدة أيضا",
        "id": "4"
    },
    {
        "name": "",
        "email": "",
        "comment": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق",
        "title": "منتج رائع. التعبئة والتغليف كانت جيدة أيضا",
        "id": "5"
    },
    {
        "name": "",
        "email": "",
        "comment": "مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة vv nnnnnnn nnnnn nnnnnnnn nnnnnnnn nnnnnnnnnn  ffffffffff عدد الحروف التى يولدها التطبيق",
        "title": "vmm vnc nn nnnnnn vvvvv vvvvvvvvvvv  vvvvvvvvvvvv vvvvvvvvvvvv vvvvvvvvvvvvv vvvvvvvvvvv vvvvvv vvvvvvv vvvvvvv vvvvvvvvv vvvvvvvvvv vvvvvvvvvvvvvvv vvvvvvvvvvvvvvv vvvvvvvvv vvvvvv منتج رائع. التعبئة والتغليف كانت جيدة أيضا",
        "id": "6"
    }
];